### PR TITLE
Expose PresenterLifeCycleLinker as public

### PR DESCRIPTION
**Pull request by pakoito**
This change allows using part of the Rosie stack without requiring inheritance of Fragments or Activities.

### CODE REVIEW

**Comment by pedrovgs** [comment]
I've restarted the Travis-CI build because there was a problem with the emulator :S :+1:

**Comment by pedrovgs** [comment]
@Serchinastico?

**Comment by Serchinastico** [comment]
LGTM

**Comment by pedrovgs** [comment]
Thanks for your PR @pakoito! We will release a new version once I finish some changes related to the PresenterLifecycleLinker public API.

**Pull request merged**
